// <auto-generated />
using System;
using APIAnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIAnimalShelter.Migrations
{
    [DbContext(typeof(APIAnimalShelterContext))]
    [Migration("20210122192618_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("APIAnimalShelter.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Breed");

                    b.Property<string>("Coloring");

                    b.Property<DateTime>("DateAvailable");

                    b.Property<string>("Name");

                    b.Property<string>("Personality");

                    b.Property<string>("Sex");

                    b.HasKey("CatId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            Age = 3,
                            Breed = "DSH",
                            Coloring = "Tuxedo",
                            DateAvailable = new DateTime(2021, 1, 22, 11, 26, 17, 714, DateTimeKind.Local).AddTicks(6710),
                            Name = "Boots",
                            Personality = "Boots is very curious. He plays well with cats and dogs but does not do well around children.",
                            Sex = "Male"
                        },
                        new
                        {
                            CatId = 2,
                            Age = 0,
                            Breed = "Bombay",
                            Coloring = "Black",
                            DateAvailable = new DateTime(2021, 1, 22, 11, 26, 17, 744, DateTimeKind.Local).AddTicks(3640),
                            Name = "Snowball",
                            Personality = "Snowball is 6 months old and ready for a playmate. She is very funny and acrobatic.",
                            Sex = "Female"
                        },
                        new
                        {
                            CatId = 3,
                            Age = 12,
                            Breed = "Persian",
                            Coloring = "Grey",
                            DateAvailable = new DateTime(2021, 1, 22, 11, 26, 17, 744, DateTimeKind.Local).AddTicks(3660),
                            Name = "Agatha",
                            Personality = "Agatha is a senior cat looking for her furrever lap. She loves snuggles and head pets",
                            Sex = "Female"
                        },
                        new
                        {
                            CatId = 4,
                            Age = 4,
                            Breed = "Siamese/DSH",
                            Coloring = "Flame Point",
                            DateAvailable = new DateTime(2021, 1, 22, 11, 26, 17, 744, DateTimeKind.Local).AddTicks(3670),
                            Name = "Robert",
                            Personality = "Robert loves playing tag but can get a little rowdy in his play. Might not do well around children.",
                            Sex = "Male"
                        },
                        new
                        {
                            CatId = 5,
                            Age = 7,
                            Breed = "Scottish Fold",
                            Coloring = "Silver",
                            DateAvailable = new DateTime(2021, 1, 22, 11, 26, 17, 744, DateTimeKind.Local).AddTicks(3670),
                            Name = "Squish",
                            Personality = "Squish is the best. You all are crazy if you don't try to adopt this cat right now.",
                            Sex = "Male"
                        });
                });

            modelBuilder.Entity("APIAnimalShelter.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Breed");

                    b.Property<string>("Coloring");

                    b.Property<DateTime>("DateAvailable");

                    b.Property<string>("Name");

                    b.Property<string>("Personality");

                    b.Property<string>("Sex");

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            Age = 6,
                            Breed = "American Pit Bull",
                            Coloring = "Blue grey, white",
                            DateAvailable = new DateTime(2021, 1, 22, 11, 26, 17, 745, DateTimeKind.Local).AddTicks(3080),
                            Name = "Jackson",
                            Personality = "Jackson gets easily frustrated and can exhibit this in a variety of ways. He will need positive outlets for his energy and a calm environment.",
                            Sex = "Male"
                        },
                        new
                        {
                            DogId = 2,
                            Age = 2,
                            Breed = "Mastiff",
                            Coloring = "Tan, black",
                            DateAvailable = new DateTime(2021, 1, 22, 11, 26, 17, 745, DateTimeKind.Local).AddTicks(4190),
                            Name = "Chickie",
                            Personality = "Chickie will flourish in a calm environment and a low-traffic home. She can be worried about new people, new surroundings and touch. She prefers to take things at her own pace.",
                            Sex = "Female"
                        },
                        new
                        {
                            DogId = 3,
                            Age = 3,
                            Breed = "Chihuahua/Dachshund",
                            Coloring = "TriColor",
                            DateAvailable = new DateTime(2021, 1, 22, 11, 26, 17, 745, DateTimeKind.Local).AddTicks(4210),
                            Name = "Miss Precious",
                            Personality = "Miss Precious has a history of biting a person or another animal. She would do best in an adult only home",
                            Sex = "Female"
                        },
                        new
                        {
                            DogId = 4,
                            Age = 2,
                            Breed = "Rottweiler",
                            Coloring = "Black, Tan",
                            DateAvailable = new DateTime(2021, 1, 22, 11, 26, 17, 745, DateTimeKind.Local).AddTicks(4220),
                            Name = "Zeus",
                            Personality = "Zeus had a growth mindset and loves to learn. He needs positive outlets for his energy and a calm environment.",
                            Sex = "Male"
                        },
                        new
                        {
                            DogId = 5,
                            Age = 10,
                            Breed = "Pointer/American Pit Bull",
                            Coloring = "White, Tan",
                            DateAvailable = new DateTime(2021, 1, 22, 11, 26, 17, 745, DateTimeKind.Local).AddTicks(4220),
                            Name = "Uma",
                            Personality = "Although Uma is no longer a puppy, she is still active and enjoys going for daily walks or runs. When she's not out and about, you can find her napping on a dog bed or a couch.",
                            Sex = "Female"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
